# -*- coding: utf-8 -*-
"""Statics3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKyKPZBSFSMjK2cucGAteFjx06MjQQlJ
"""

# import "array" for demonstrating array operation
import array
arr = array.array('I',[2,4,6,8,10,12])
print("Mee created array:",end="")
for I in range(0,5):
 print(arr[I],end=" ")
print("\r")

import pandas as pd
dict = {'name':["Smith","Williom","Phill","Parker"],
'age':["28","39","34","36"]}
info = pd.DataFrame(dict,index=[True,True,False,True])
print(info)

dict = {'name':["Smith","Williom","Phill","Parker"],
'age':["28","39","34","36"]}
info = pd.DataFrame(dict,index=[True,True,False,True])
print(info.loc[True])

import numpy as np
arr=np.arange(16)
print("The Original array is: \n",arr)
arr = np.arange(16).reshape(2,8)
print("\nreshapedarray.:\n",arr)
arr=np.arange(16).reshape(2,8)
print("\nreshaped array:\n",arr)