# -*- coding: utf-8 -*-
"""statics1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmiuuE_dQ_74ZzyMnWPxAZrVHOcNDFZF
"""

import pandas as pd
import numpy as np
info=np.array(['P','a','n','d','a','s'])
a=pd.Series(info)
print(a)

# a list of strings
x=['Python','Pandas']
#calling data frame constructor on list
df=pd.DataFrame(x)
print(df)

a=pd.Series(['Java','C','C++',np.nan])
a.map({'Java':'Core'})

a=pd.Series(['Java','C','C++',np.nan])
a.map({'Java':'Core'})
a.map('I like{}'.format,na_action='ignore')

s=pd.Series(["a","b","c"],
name="vals")
s.to_frame()

import matplotlib.pyplot as plt
emp=['Parker','John','Smith','William']
id=[102,107,109,114]
emp_series = pd.Series(emp)
id_series=pd.Series(id)
frame={'Emp':emp_series,'ID':id_series}
result=pd.DataFrame(frame)
print(result)